# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatWindow(object):
    def setupUi(self, ChatWindow):
        ChatWindow.setObjectName("ChatWindow")
        ChatWindow.resize(912, 596)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        ChatWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ChatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AllText = QtWidgets.QTextEdit(self.centralwidget)
        self.AllText.setGeometry(QtCore.QRect(10, 70, 891, 371))
        self.AllText.setObjectName("AllText")
        self.SendText = QtWidgets.QTextEdit(self.centralwidget)
        self.SendText.setGeometry(QtCore.QRect(20, 460, 721, 121))
        self.SendText.setObjectName("SendText")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(760, 490, 131, 51))
        self.SendButton.setObjectName("SendButton")
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectButton.setGeometry(QtCore.QRect(620, 10, 131, 51))
        self.ConnectButton.setObjectName("ConnectButton")
        self.StopButton = QtWidgets.QPushButton(self.centralwidget)
        self.StopButton.setGeometry(QtCore.QRect(770, 10, 131, 51))
        self.StopButton.setObjectName("StopButton")
        self.IPText = QtWidgets.QLineEdit(self.centralwidget)
        self.IPText.setGeometry(QtCore.QRect(60, 20, 261, 41))
        self.IPText.setObjectName("IPText")
        self.IPLabel = QtWidgets.QLabel(self.centralwidget)
        self.IPLabel.setGeometry(QtCore.QRect(20, 30, 31, 21))
        self.IPLabel.setObjectName("IPLabel")
        self.PortText = QtWidgets.QLineEdit(self.centralwidget)
        self.PortText.setGeometry(QtCore.QRect(410, 20, 131, 41))
        self.PortText.setObjectName("PortText")
        self.PortLabel = QtWidgets.QLabel(self.centralwidget)
        self.PortLabel.setGeometry(QtCore.QRect(350, 30, 71, 21))
        self.PortLabel.setObjectName("PortLabel")
        ChatWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChatWindow)
        QtCore.QMetaObject.connectSlotsByName(ChatWindow)

    def retranslateUi(self, ChatWindow):
        _translate = QtCore.QCoreApplication.translate
        ChatWindow.setWindowTitle(_translate("ChatWindow", "ChatWindow"))
        self.SendButton.setText(_translate("ChatWindow", "Send"))
        self.ConnectButton.setText(_translate("ChatWindow", "Connect"))
        self.StopButton.setText(_translate("ChatWindow", "Stop"))
        self.IPLabel.setText(_translate("ChatWindow", "IP"))
        self.PortLabel.setText(_translate("ChatWindow", "Port"))
